@baseUrl = http://localhost:3000

### AppControllerGetHello
# @name AppControllerGetHello
GET {{baseUrl}}/home/hello


### AppControllerGetExemplo
# @name ExemploDeRota
GET {{baseUrl}}/home/newRoute


### ConceitosManualController home
# @name ExemploManual
GET {{baseUrl}}/conceitos-manual


### ConceitosAutomaticoController home
# @name ExemploAutomatico
GET {{baseUrl}}/conceitos-automatico

### TaskController listTask
# @name ListarTarefas
GET {{baseUrl}}/task/listTask

### ===================================
### Seção 4 - RECADOS

### Retorna todas as rotas
# @name RecadosFindAll
GET {{baseUrl}}/recados

### Retorna apenas uma rota
# @name RecadosFindOne
GET {{baseUrl}}/recados/1

### Cria um novo recado
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "recado": "Este é o que estou enviando.",
    "nova chave": "Outro valor"
}

### Atualiza meu recado
PATCH  {{baseUrl}}/recados/1
Content-Type: application/json

{
    "recado": "Este é o que estou enviando.",
    "atulizar": true
}

### Deleta um recado
DELETE  {{baseUrl}}/recados/1

### Rota com parâmetros
# @name finAllParameters
GET {{baseUrl}}/recados/
?limit=5&offset=5