@baseUrl = http://localhost:3000

### AppControllerGetHello
# @name AppControllerGetHello
GET {{baseUrl}}/home/hello


### AppControllerGetExemplo
# @name ExemploDeRota
GET {{baseUrl}}/home/newRoute


### ConceitosManualController home
# @name ExemploManual
GET {{baseUrl}}/conceitos-manual


### ConceitosAutomaticoController home
# @name ExemploAutomatico
GET {{baseUrl}}/conceitos-automatico

### TaskController listTask
# @name ListarTarefas
GET {{baseUrl}}/task/listTask

### ===================================
### Seção 4 - RECADOS

### Retorna todas as rotas
# @name Recados/FindAll
GET {{baseUrl}}/recados

### Retorna apenas um id
# @name Recados/FindOneService
GET {{baseUrl}}/recados/2

### Cria um novo recado
# @name Recados/CreateService
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "texto": "3 - NOVO Recado",
    "de": "Joana",
    "para": "João",
    "lido": false,
    "data": "2025-05-01T23:39:17.281Z"
}

### Atualiza meu recado
PATCH  {{baseUrl}}/recados/2
Content-Type: application/json

{
    "texto": "Atualizei meu recado - 2",
    "de": "Joana",
    "para": "João",
    "lido": false,
    "data": "2025-05-01T23:39:17.281Z"
}

### Deleta um recado
DELETE  {{baseUrl}}/recados/2

### Rota com parâmetros
# @name finAllParameters
GET {{baseUrl}}/recados/
?limit=10
&offset=0